[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DMFRC522_SPICLOCK=500000

lib_deps =
    miguelbalboa/MFRC522
    bblanchon/ArduinoJson
    knolleary/PubSubClient
    chris--a/Keypad
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    adafruit/RTClib @ ^2.1.4

[env:native]
platform = native
test_build_src = true

build_flags =
    -std=c++17
    -DARDUINOJSON_ENABLE_STD_STRING=1

lib_deps =
    bblanchon/ArduinoJson

build_src_filter =
    -<*>
    +<CardReader.cpp>
    +<MqttManager.cpp>
    +<DoorState.cpp>
    +<AccessControl.cpp>
