; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
	miguelbalboa/MFRC522
	bblanchon/ArduinoJson
	knolleary/PubSubClient
	chris--a/Keypad

[env:native]
platform = native
test_build_src = true
build_flags = 
        -std=c++17
        -DARDUINOJSON_ENABLE_STD_STRING=1
lib_deps = 
        bblanchon/ArduinoJson
build_src_filter = 
        -<*>
        +<CardReader.cpp>
        +<MqttManager.cpp>
        +<DoorState.cpp>
        +<AccessControl.cpp>